apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: channels.kinesiscontroller.triggermesh.dev
spec:
  group: kinesiscontroller.triggermesh.dev
  version: v1alpha1
  names:
    kind: Channel
    plural: channels
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        spec:
          properties:
            replicas:
              type: integer
              minimum: 1
              maximum: 10
